const fs = require("fs");
const path = require("path");

// Logging in inside our own window sidesteps the whole "read the cookies out of
// an installed browser" problem: no locked SQLite files, no DPAPI, and no
// App-Bound Encryption. The user scans a QR code once, we keep the session in a
// persistent partition, and we hand yt-dlp a plain Netscape cookie jar.

// A real Chrome UA — sites (bilibili in particular) serve degraded or blocked
// pages to the default Electron UA.
const CHROME_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) " +
  "Chrome/131.0.0.0 Safari/537.36";

// `success` is the cookie whose presence means the login completed, so we can
// close the window automatically instead of making the user do it.
const SITES = [
  {
    key: "bilibili",
    name: "哔哩哔哩",
    match: /(^|\.)bilibili\.com$/i,
    domain: "bilibili.com",
    loginUrl: "https://passport.bilibili.com/login",
    success: "SESSDATA",
  },
  {
    key: "youtube",
    name: "YouTube",
    match: /(^|\.)(youtube\.com|youtu\.be)$/i,
    domain: "youtube.com",
    loginUrl: "https://accounts.google.com/ServiceLogin?service=youtube",
    success: "SID",
  },
  {
    key: "douyin",
    name: "抖音",
    match: /(^|\.)douyin\.com$/i,
    domain: "douyin.com",
    loginUrl: "https://www.douyin.com/",
    success: "sessionid",
  },
];

function baseDomainOf(hostname) {
  const labels = String(hostname || "").split(".").filter(Boolean);
  if (labels.length <= 2) return labels.join(".");
  return labels.slice(-2).join(".");
}

// Resolve the site to log into from the video URL the user pasted. Unknown
// sites still work: we open their homepage and export whatever cookies exist
// when the user closes the window.
function siteForUrl(url) {
  let hostname = "";
  try {
    hostname = new URL(String(url || "")).hostname;
  } catch {
    return null;
  }
  if (!hostname) return null;
  const known = SITES.find((site) => site.match.test(hostname));
  if (known) return known;
  const domain = baseDomainOf(hostname);
  return { key: domain, name: domain, domain, loginUrl: `https://${hostname}/`, success: "" };
}

function toNetscape(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by video-download", ""];
  for (const c of cookies) {
    if (!c.name) continue;
    const includeSubdomains = c.domain.startsWith(".") ? "TRUE" : "FALSE";
    const expiry = c.session || !c.expirationDate ? 0 : Math.floor(c.expirationDate);
    const row = [
      c.domain,
      includeSubdomains,
      c.path || "/",
      c.secure ? "TRUE" : "FALSE",
      expiry,
      c.name,
      c.value,
    ].join("\t");
    lines.push(c.httpOnly ? `#HttpOnly_${row}` : row);
  }
  return `${lines.join("\n")}\n`;
}

function createLogin({ app, BrowserWindow, session, getMainWindow, logEvent }) {
  let activeWindow = null;

  function cookieDir() {
    return path.join(app.getPath("userData"), "cookies");
  }
  function cookieFileFor(site) {
    return path.join(cookieDir(), `${site.domain.replace(/[^a-z0-9.-]/gi, "_")}.txt`);
  }
  // One partition per site keeps sessions independent and, being persistent,
  // survives app restarts — so the QR scan is a one-time cost.
  function partitionFor(site) {
    return `persist:login-${site.domain.replace(/[^a-z0-9.-]/gi, "_")}`;
  }

  async function readCookies(site) {
    const ses = session.fromPartition(partitionFor(site));
    return ses.cookies.get({ domain: site.domain });
  }

  async function writeJar(site, cookies) {
    const file = cookieFileFor(site);
    await fs.promises.mkdir(path.dirname(file), { recursive: true });
    await fs.promises.writeFile(file, toNetscape(cookies), { mode: 0o600 });
    return file;
  }

  function isLoggedIn(site, cookies) {
    if (!site.success) return cookies.length > 0;
    return cookies.some((c) => c.name === site.success && c.value);
  }

  // Snapshot of what we already have on disk, so the UI can say "已登录" and
  // skip the window entirely.
  async function status(url) {
    const site = siteForUrl(url);
    if (!site) return { ok: false, error: "请先填写视频 URL" };
    const file = cookieFileFor(site);
    let updatedAt = 0;
    try {
      updatedAt = (await fs.promises.stat(file)).mtimeMs;
    } catch {
      return { ok: true, site: site.key, name: site.name, hasCookies: false };
    }
    const cookies = await readCookies(site);
    return {
      ok: true,
      site: site.key,
      name: site.name,
      hasCookies: true,
      loggedIn: isLoggedIn(site, cookies),
      file,
      count: cookies.length,
      updatedAt,
      userAgent: CHROME_UA,
    };
  }

  async function clear(url) {
    const site = siteForUrl(url);
    if (!site) return { ok: false, error: "请先填写视频 URL" };
    const ses = session.fromPartition(partitionFor(site));
    await ses.clearStorageData({ storages: ["cookies"] });
    await fs.promises.rm(cookieFileFor(site), { force: true });
    logEvent("info", "Cleared in-app login", { site: site.key });
    return { ok: true, site: site.key, name: site.name };
  }

  async function open(url) {
    const site = siteForUrl(url);
    if (!site) return { ok: false, error: "请先填写视频 URL，再登录对应站点" };
    if (activeWindow && !activeWindow.isDestroyed()) {
      activeWindow.focus();
      return { ok: false, error: "登录窗口已打开" };
    }

    const ses = session.fromPartition(partitionFor(site));
    ses.setUserAgent(CHROME_UA);

    const win = new BrowserWindow({
      width: 1000,
      height: 720,
      parent: getMainWindow() || undefined,
      title: `登录 ${site.name}`,
      autoHideMenuBar: true,
      webPreferences: {
        partition: partitionFor(site),
        contextIsolation: true,
        nodeIntegration: false,
        // No preload: this window renders a third-party page and must not see
        // any of our IPC surface.
        sandbox: true,
      },
    });
    activeWindow = win;
    logEvent("info", "Opening login window", { site: site.key, url: site.loginUrl });

    return new Promise((resolve) => {
      let settled = false;
      let timer = null;

      const finish = async (reason) => {
        if (settled) return;
        settled = true;
        if (timer) clearInterval(timer);
        let cookies = [];
        try {
          cookies = await readCookies(site);
        } catch (error) {
          logEvent("warn", "Reading login cookies failed", { error: error.message });
        }
        const loggedIn = isLoggedIn(site, cookies);
        let file = "";
        // Even a manual close is worth saving: partial cookies still beat none,
        // and unknown sites have no success marker to wait for.
        if (cookies.length) {
          try {
            file = await writeJar(site, cookies);
          } catch (error) {
            logEvent("error", "Writing cookie jar failed", { error: error.message });
          }
        }
        logEvent("info", "Login window closed", { site: site.key, reason, loggedIn, count: cookies.length });
        if (!win.isDestroyed()) win.close();
        activeWindow = null;
        resolve({
          ok: loggedIn && !!file,
          canceled: reason === "closed" && !loggedIn,
          site: site.key,
          name: site.name,
          loggedIn,
          file,
          count: cookies.length,
          userAgent: CHROME_UA,
          error: loggedIn ? "" : `未检测到 ${site.name} 的登录态`,
        });
      };

      // Poll rather than listen to `cookies-changed`: the marker cookie can be
      // set by a background XHR the window never navigates for.
      timer = setInterval(async () => {
        if (settled) return;
        try {
          const cookies = await readCookies(site);
          if (isLoggedIn(site, cookies)) finish("logged-in");
        } catch {
          /* window may be tearing down */
        }
      }, 1500);

      win.on("closed", () => {
        activeWindow = null;
        finish("closed");
      });

      win.loadURL(site.loginUrl, { userAgent: CHROME_UA }).catch((error) => {
        logEvent("error", "Login page failed to load", { site: site.key, error: error.message });
      });
    });
  }

  function closeActive() {
    if (activeWindow && !activeWindow.isDestroyed()) activeWindow.close();
  }

  return { open, status, clear, closeActive, siteForUrl };
}

module.exports = { createLogin, toNetscape, siteForUrl };
